"""Обновление модели User

Revision ID: 6d6fbfff6f09
Revises: 
Create Date: 2025-03-02 17:07:01.889617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6fbfff6f09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_experience', sa.Integer(), nullable=True))
        batch_op.drop_column('hire_date')
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('work_experience')

    # ### end Alembic commands ###
