"""course model

Revision ID: 8f5cc7b30bc0
Revises: 3b61b27cb485
Create Date: 2025-03-27 22:29:27.974145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5cc7b30bc0'
down_revision = '76f548588f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.TEXT(), nullable=True))
        batch_op.create_unique_constraint(None, ['course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('type')
        batch_op.drop_column('price')
        batch_op.drop_column('description')
        batch_op.drop_column('duration')
        batch_op.drop_column('link')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
