name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: tsvetkovskiy_tests  # Переключаемся на ветку с тестами

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Укажите нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Установите зависимости, если есть requirements.txt
        pip install pytest  # Устанавливаем pytest

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}  # Добавляем корень проекта в PYTHONPATH
      run: python -m pytest backend/tests  # Запуск тестов
